In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Seaborn stilini ayarla
sns.set(style="whitegrid")

In [2]:
dosya_yolu = 'All_Orders_Ürün_İsimleri.csv'
df = pd.read_csv(dosya_yolu)

# Tüm sütunları görüntülemek için pandas ayarlarını değiştir
pd.set_option('display.max_columns', None)

df.head()

,Unnamed: 0.1,Unnamed: 0,order_id,purchase_date,last_updated_date,order_status,fulfillment,sales_channel,ship_service_level,asin,item_status,quantity,currency,item_price,item_tax,ship_city,ship_country,business_order,amazon_invoiced,vat_exclusive_item_price,vat_shipping_price,product,sentetik_maliyet,sentetik_maliyet(€),item_price(€),vat_exclusive_item_price(€),item_tax(€),vat_exclusive_shipping_price(€),Product Name,Categori,totall_saless(€)
0,0,0,403-3538797-3315514,30/05/2024,30/05/2024,Pending,Amazon,Fransa,Standard,B0BG6C5W29,Unshipped,1,EUR,21.92,0.75,Rodez,FR,False,False,0.00,0.00,Bioblas knoblauch sparset l schwarzer knoblauc...,19.588480,19.588480,21.92,0.00,0.75,0.00,Bioblas Siyah Sarımsak Özlü Şampuan (1000 ml) ...,Kozmetik,21.92
1,1,16,407-1529181-3128329,22/05/2024,30/05/2024,Pending,Amazon,Fransa,Standard,B0BG6C5W29,Unshipped,1,EUR,21.92,0.75,Champigny sur marne,FR,False,False,0.00,0.00,Bioblas knoblauch sparset l schwarzer knoblauc...,19.203247,19.203247,21.92,0.00,0.75,0.00,Bioblas Siyah Sarımsak Özlü Şampuan (1000 ml) ...,Kozmetik,21.92
2,2,48,402-0925298-6082759,12/05/2024,13/05/2024,Shipped,Amazon,Fransa,Standard,B0BG6C5W29,Shipped,1,EUR,21.94,1.14,Nancy,FR,False,True,20.80,0.00,Bioblas knoblauch sparset l schwarzer knoblauc...,20.550706,20.550706,21.94,20.80,1.14,0.00,Bioblas Siyah Sarımsak Özlü Şampuan (1000 ml) ...,Kozmetik,21.94
3,3,65,171-6046087-3781929,04/05/2024,13/05/2024,Shipped,Amazon,Fransa,Standard,B0BG6C5W29,Shipped,1,EUR,21.92,0.75,Payerne,CH,False,True,21.92,6.99,Bioblas knoblauch sparset l schwarzer knoblauc...,20.509975,20.509975,21.92,21.92,0.75,6.99,Bioblas Siyah Sarımsak Özlü Şampuan (1000 ml) ...,Kozmetik,21.92
4,4,69,408-0925601-9533151,03/05/2024,06/05/2024,Shipped,Amazon,Fransa,Expedited,B0BG6C5W29,Shipped,1,EUR,18.27,0.75,Augny,FR,False,True,18.27,0.00,Bioblas knoblauch sparset l schwarzer knoblauc...,19.123606,19.123606,18.27,18.27,0.75,0.00,Bioblas Siyah Sarımsak Özlü Şampuan (1000 ml) ...,Kozmetik,18.27

In [3]:
sütun_isimleri = df.columns.tolist()
print("Sütun İsimleri:\n", sütun_isimleri)

Sütun İsimleri:
 ['Unnamed: 0.1', 'Unnamed: 0', 'order_id', 'purchase_date', 'last_updated_date', 'order_status', 'fulfillment', 'sales_channel', 'ship_service_level', 'asin', 'item_status', 'quantity', 'currency', 'item_price', 'item_tax', 'ship_city', 'ship_country', 'business_order', 'amazon_invoiced', 'vat_exclusive_item_price', 'vat_shipping_price', 'product', 'sentetik_maliyet', 'sentetik_maliyet(€)', 'item_price(€)', 'vat_exclusive_item_price(€)', 'item_tax(€)', 'vat_exclusive_shipping_price(€)', 'Product Name', 'Categori', 'totall_saless(€)']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123772 entries, 0 to 123771
Data columns (total 31 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Unnamed: 0.1                     123772 non-null  int64
 1   Unnamed: 0                       123772 non-null  int64
 2   order_id                         123772 non-null  object
 3   purchase_date                    123772 non-null  object
 4   last_updated_date                123772 non-null  object
 5   order_status                     123772 non-null  object
 6   fulfillment                      123772 non-null  object
 7   sales_channel                    123772 non-null  object
 8   ship_service_level               123772 non-null  object
 9   asin                             123772 non-null  object
 10  item_status                      123772 non-null  object
 11  quantity                         123772 non-null  int64
 12  currency                         123772 non-null  object
 13  item_price                       123772 non-null  float64
 14  item_tax                         123772 non-null  float64
 15  ship_city                        123772 non-null  object
 16  ship_country                     123772 non-null  object
 17  business_order                   123772 non-null  bool
 18  amazon_invoiced                  123772 non-null  bool
 19  vat_exclusive_item_price         123772 non-null  float64
 20  vat_shipping_price               123772 non-null  float64
 21  product                          123772 non-null  object
 22  sentetik_maliyet                 123772 non-null  float64
 23  sentetik_maliyet(€)              123772 non-null  float64
 24  item_price(€)                    123772 non-null  float64
 25  vat_exclusive_item_price(€)      123772 non-null  float64
 26  item_tax(€)                      123772 non-null  float64
 27  vat_exclusive_shipping_price(€)  123772 non-null  float64
 28  Product Name                     123772 non-null  object
 29  Categori                         123661 non-null  object
 30  totall_saless(€)                 123772 non-null  float64
dtypes: bool(2), float64(11), int64(3), object(15)
memory usage: 27.6+ MB

In [5]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,quantity,item_price,item_tax,vat_exclusive_item_price,vat_shipping_price,sentetik_maliyet,sentetik_maliyet(€),item_price(€),vat_exclusive_item_price(€),item_tax(€),vat_exclusive_shipping_price(€),totall_saless(€)
count,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000,123772.000000
mean,61885.500000,61899.253523,1.187660,13.086098,1.383471,11.339020,0.267936,12.110965,11.715485,12.660199,10.970914,1.328509,0.238067,22.112616
std,35730.043096,35739.480020,0.902124,17.087140,2.010422,15.544418,1.224028,16.092918,13.875101,14.716660,13.598763,1.573943,0.832415,172.790568
min,0.000000,0.000000,0.000000,0.000000,0.120000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.066750,0.000000,0.000000
25%,30942.750000,30947.750000,1.000000,5.980000,0.560000,4.040000,0.000000,5.392133,5.366694,5.950000,4.030000,0.560000,0.000000,4.790000
50%,61885.500000,61898.500000,1.000000,9.890000,0.750000,8.400000,0.000000,9.013024,8.995382,9.890000,8.400000,0.750000,0.000000,9.690000
75%,92828.250000,92850.250000,1.000000,15.890000,1.540000,14.240000,0.000000,14.798176,14.709175,15.890000,14.190000,1.530000,0.000000,17.850000
max,123771.000000,123801.000000,40.000000,1062.250000,121.620000,992.750000,58.040000,1041.517203,1041.517203,1062.250000,992.750000,80.220000,37.500000,26556.250000

In [6]:
eksik_degerler = df.isnull().sum()
print("Her sütundaki eksik değerler:\n", eksik_degerler)

Her sütundaki eksik değerler:
 Unnamed: 0.1                         0
Unnamed: 0                           0
order_id                             0
purchase_date                        0
last_updated_date                    0
order_status                         0
fulfillment                          0
sales_channel                        0
ship_service_level                   0
asin                                 0
item_status                          0
quantity                             0
currency                             0
item_price                           0
item_tax                             0
ship_city                            0
ship_country                         0
business_order                       0
amazon_invoiced                      0
vat_exclusive_item_price             0
vat_shipping_price                   0
product                              0
sentetik_maliyet                     0
sentetik_maliyet(€)                  0
item_price(€)                        0
vat_exclusive_item_price(€)          0
item_tax(€)                          0
vat_exclusive_shipping_price(€)      0
Product Name                         0
Categori                           111
totall_saless(€)                     0
dtype: int64

In [1]:
en_yaygin_item_status = df['item_status'].mode()[0]
df['item_status'].fillna(en_yaygin_item_status, inplace=True)

NameError: name 'df' is not defined

In [2]:
en_yaygin_ship_city = df['ship_city'].mode()[0]
df['ship_city'].fillna(en_yaygin_ship_city, inplace=True)

NameError: name 'df' is not defined